version: "1.1"
name: Status Check
env:
  host: localhost:3000
tests:
  example:
    steps:
      - name: GET request
        http:
          url: http://${{env.host}}
          method: GET
          check:
            status: /^20/